/**
 * Deterministic mock provider — no network, no API key, always available.
 * Default per Implementation Decision Log — Decision I.
 */
import type { AiProvider, AiProviderResult, ExplainProjectContext } from "./provider.js";

export class MockProvider implements AiProvider {
  readonly mode = "mock" as const;

  async explainProject(context: ExplainProjectContext): Promise<AiProviderResult> {
    const techList = context.technologies.map((t) => t.name).join(", ") || "no clearly detected technologies";
    const lines = [
      `${context.projectName} looks like a ${context.category.toLowerCase()} (${context.projectType}).`,
      context.description,
      `Technology signals: ${techList}.`,
      context.architectureSummary,
      context.healthSummary,
      "(Generated by the offline mock AI provider — set AI_PROVIDER=anthropic and provide ANTHROPIC_API_KEY for a real model-generated explanation.)",
    ];
    return { text: lines.filter(Boolean).join(" "), providerMode: "mock" };
  }
}
